services:
  - postgres
  - node
variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: ece651
  POSTGRES_USER: ece651_admin
  POSTGRES_PASSWORD: YbRvAizCTnbQ5W6JI69h
  PG_SCRAPER_USER: ece651_scraper
  PG_SCRAPER_PASS: wxJcTdJYUU3mMAsAa5YD
  PG_ML_USER: ece651_ml
  PG_ML_PASS: TVL3MV0mguz0DOhLbbm2
  PG_WEB_USER: ece651_web
  PG_WEB_PASS: dm2fBdodbrHPtJVvlSKF
connect:
  only:
    - tags
    - triggers
  stage: build
  image: postgres
  script:
    # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create-users_postgre.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create_tables_insert_data/AmazonDetails.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create_tables_insert_data/Author.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create_tables_insert_data/AuthorBooks.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create_tables_insert_data/BookCategories.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create_tables_insert_data/BookOfTheDay.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create_tables_insert_data/Books.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create_tables_insert_data/Categories.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create_tables_insert_data/Reviews.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create_tables_insert_data/Users.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/create_tables_insert_data/Views.sql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q -f src/db/grant_tables_add_constraint.sql
    - export PGPASSWORD=$PG_SCRAPER_PASS
    - psql -h "postgres" -U "$PG_SCRAPER_USER" -d "$POSTGRES_DB" -c 'SELECT * FROM public."BookOfTheDay";'
    - export PGPASSWORD=$PG_ML_PASS
    - psql -h "postgres" -U "$PG_ML_USER" -d "$POSTGRES_DB" -c 'SELECT * FROM public."Books";'
    - export PGPASSWORD=$PG_WEB_PASS
    - psql -h "postgres" -U "$PG_WEB_USER" -d "$POSTGRES_DB" -c 'SELECT * FROM public."Users";'
node version:
  only:
    - tags
    - triggers
  stage: test
  image: node
  script:
    - node --version