stages:
  - lint-css
  - lint-js
  - unit-test

image: node:6.11.2


lint css:
  stage: lint-css
  before_script:
    - npm install
  only:
    - master
  script:
    - cd src/web
    - node node_modules/gulp/bin/gulp.js lint-css

lint js:
  stage: lint-js
  only:
    - master
  script:
    - cd src/web
    - node node_modules/gulp/bin/gulp.js lint-js

run unit test:
  stage: unit-test
  only:
    - master
  script:
    - cd src/web
    - node node_modules/gulp/bin/gulp.js test